version: '3.1'

services:
  changjin_upload:
    image: changjinkube/knu_shoppingmall:flask
    # build: ./Flask
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    ports:
      - 5051:5051
      - 923:80

networks:
  default:
    external:
      name: mongo_default